// Mock Xtream Codes API data — all content is public domain / Creative Commons

export const AUTH = {
  username: "samsung_qa",
  password: "test2026",
};

// ── Posters (public domain / CC images) ──────────────────────────────────

const POSTERS = {
  bigBuckBunny:
    "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Big_buck_bunny_poster_big.jpg/440px-Big_buck_bunny_poster_big.jpg",
  sintel:
    "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Sintel_poster.jpg/440px-Sintel_poster.jpg",
  tearsOfSteel:
    "https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Tears_of_Steel_poster.jpg/440px-Tears_of_Steel_poster.jpg",
  elephantsDream:
    "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Elephants_Dream_s5_both.jpg/440px-Elephants_Dream_s5_both.jpg",
  testPattern:
    "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/PNG_transparency_demonstration_1.png/280px-PNG_transparency_demonstration_1.png",
  nature:
    "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/24422_Diadema_antillarum.jpg/440px-24422_Diadema_antillarum.jpg",
  blenderSeries:
    "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Blender_logo_no_text.svg/440px-Blender_logo_no_text.svg.png",
};

// ── Stream URLs ──────────────────────────────────────────────────────────

export const STREAM_URLS: Record<number, string> = {
  // VOD (stream_id → URL)
  1: "https://commondatastorage.googleapis.com/gtv-videos-bucket/CastVideos/mp4/BigBuckBunny.mp4",
  2: "https://commondatastorage.googleapis.com/gtv-videos-bucket/CastVideos/mp4/Sintel.mp4",
  3: "https://commondatastorage.googleapis.com/gtv-videos-bucket/CastVideos/mp4/TearsOfSteel.mp4",
  4: "https://commondatastorage.googleapis.com/gtv-videos-bucket/CastVideos/mp4/ElephantsDream.mp4",
  // Live — Free-TV public channels (HLS)
  101: "https://news.cgtn.com/resource/live/english/cgtn-e.m3u8",
  102: "https://news.cgtn.com/resource/live/french/cgtn-f.m3u8",
  103: "https://news.cgtn.com/resource/live/document/cgtn-d.m3u8",
  104: "https://live-hls-web-aje.getaj.net/AJE/01.m3u8",
  105: "https://live-hls-web-aje.getaj.net/FRANCE24/01.m3u8",
  106: "https://dwamdstream104.akamaized.net/hls/live/2015530/dwstream104/index.m3u8",
  107: "https://live-01-02-shsm.vos.cienradios.com/CINEAR/tracks-v1a1/mono.m3u8",
  108: "https://live-01-02-shsm.vos.cienradios.com/DEPORTV/tracks-v1a1/mono.m3u8",
  109: "https://live-01-02-shsm.vos.cienradios.com/TVP/tracks-v1a1/mono.m3u8",
  110: "https://live-01-02-shsm.vos.cienradios.com/ENCUENTRO/tracks-v1a1/mono.m3u8",
  // Test streams
  111: "https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8",
  112: "https://cph-p2p-msl.akamaized.net/hls/live/2000341/test/master.m3u8",
  // Series episodes reuse VOD URLs
  1001: "https://commondatastorage.googleapis.com/gtv-videos-bucket/CastVideos/mp4/BigBuckBunny.mp4",
  1002: "https://commondatastorage.googleapis.com/gtv-videos-bucket/CastVideos/mp4/Sintel.mp4",
  1003: "https://commondatastorage.googleapis.com/gtv-videos-bucket/CastVideos/mp4/TearsOfSteel.mp4",
};

// ── VOD Categories ───────────────────────────────────────────────────────

export const VOD_CATEGORIES = [
  { category_id: "1", category_name: "Animation", parent_id: 0 },
  { category_id: "2", category_name: "Sci-Fi", parent_id: 0 },
];

// ── VOD Streams ──────────────────────────────────────────────────────────

export const VOD_STREAMS = [
  {
    num: 1,
    name: "Big Buck Bunny",
    stream_type: "movie",
    stream_id: 1,
    stream_icon: POSTERS.bigBuckBunny,
    rating: "8.0",
    rating_5based: 4.0,
    added: "1704067200",
    category_id: "1",
    container_extension: "mp4",
    custom_sid: "",
    direct_source: "",
  },
  {
    num: 2,
    name: "Sintel",
    stream_type: "movie",
    stream_id: 2,
    stream_icon: POSTERS.sintel,
    rating: "7.5",
    rating_5based: 3.8,
    added: "1704067200",
    category_id: "1",
    container_extension: "mp4",
    custom_sid: "",
    direct_source: "",
  },
  {
    num: 3,
    name: "Tears of Steel",
    stream_type: "movie",
    stream_id: 3,
    stream_icon: POSTERS.tearsOfSteel,
    rating: "7.0",
    rating_5based: 3.5,
    added: "1704067200",
    category_id: "2",
    container_extension: "mp4",
    custom_sid: "",
    direct_source: "",
  },
  {
    num: 4,
    name: "Elephant's Dream",
    stream_type: "movie",
    stream_id: 4,
    stream_icon: POSTERS.elephantsDream,
    rating: "6.5",
    rating_5based: 3.3,
    added: "1704067200",
    category_id: "2",
    container_extension: "mp4",
    custom_sid: "",
    direct_source: "",
  },
];

// ── VOD Info (detailed) ──────────────────────────────────────────────────

export const VOD_INFO: Record<number, object> = {
  1: {
    info: {
      movie_image: POSTERS.bigBuckBunny,
      tmdb_id: 10378,
      name: "Big Buck Bunny",
      o_name: "Big Buck Bunny",
      cover_big: POSTERS.bigBuckBunny,
      release_date: "2008-04-10",
      youtube_trailer: "YE7VzlLtp-4",
      director: "Sacha Goedegebure",
      actors: "N/A",
      cast: "N/A",
      description:
        "A large and lovable rabbit deals with three tiny bullies, led by a flying squirrel, who are determined to squelch his happiness.",
      plot: "A large and lovable rabbit deals with three tiny bullies, led by a flying squirrel, who are determined to squelch his happiness.",
      age: "",
      mpaa_rating: "G",
      rating_count_kinopoisk: 0,
      country: "Netherlands",
      genre: "Animation, Comedy, Short",
      duration_secs: 596,
      duration: "00:09:56",
      bitrate: 0,
      video: {},
      audio: {},
    },
    movie_data: {
      stream_id: 1,
      name: "Big Buck Bunny",
      added: "1704067200",
      category_id: "1",
      container_extension: "mp4",
      custom_sid: "",
      direct_source: "",
    },
  },
  2: {
    info: {
      movie_image: POSTERS.sintel,
      tmdb_id: 45745,
      name: "Sintel",
      o_name: "Sintel",
      cover_big: POSTERS.sintel,
      release_date: "2010-09-30",
      youtube_trailer: "eRsGyueVLvQ",
      director: "Colin Levy",
      actors: "Halina Reijn, Thom Hoffman",
      cast: "Halina Reijn, Thom Hoffman",
      description:
        "A lonely young woman, Sintel, helps and befriends a dragon, whom she calls Scales. But when he is taken from her, she must embark on a dangerous quest to find her best friend.",
      plot: "A lonely young woman, Sintel, helps and befriends a dragon, whom she calls Scales. But when he is taken from her, she must embark on a dangerous quest to find her best friend.",
      age: "",
      mpaa_rating: "PG",
      rating_count_kinopoisk: 0,
      country: "Netherlands",
      genre: "Animation, Fantasy, Short",
      duration_secs: 888,
      duration: "00:14:48",
      bitrate: 0,
      video: {},
      audio: {},
    },
    movie_data: {
      stream_id: 2,
      name: "Sintel",
      added: "1704067200",
      category_id: "1",
      container_extension: "mp4",
      custom_sid: "",
      direct_source: "",
    },
  },
  3: {
    info: {
      movie_image: POSTERS.tearsOfSteel,
      tmdb_id: 129542,
      name: "Tears of Steel",
      o_name: "Tears of Steel",
      cover_big: POSTERS.tearsOfSteel,
      release_date: "2012-09-26",
      youtube_trailer: "R6MlUcmOul8",
      director: "Ian Hubert",
      actors: "Derek de Lint, Sergio Hasselbaink",
      cast: "Derek de Lint, Sergio Hasselbaink",
      description:
        "In an apocalyptic future, a group of soldiers and scientists takes refuge in Amsterdam to try to stop an army of robots that threatens the planet.",
      plot: "In an apocalyptic future, a group of soldiers and scientists takes refuge in Amsterdam to try to stop an army of robots that threatens the planet.",
      age: "",
      mpaa_rating: "PG-13",
      rating_count_kinopoisk: 0,
      country: "Netherlands",
      genre: "Sci-Fi, Short",
      duration_secs: 734,
      duration: "00:12:14",
      bitrate: 0,
      video: {},
      audio: {},
    },
    movie_data: {
      stream_id: 3,
      name: "Tears of Steel",
      added: "1704067200",
      category_id: "2",
      container_extension: "mp4",
      custom_sid: "",
      direct_source: "",
    },
  },
  4: {
    info: {
      movie_image: POSTERS.elephantsDream,
      tmdb_id: 10895,
      name: "Elephant's Dream",
      o_name: "Elephant's Dream",
      cover_big: POSTERS.elephantsDream,
      release_date: "2006-03-24",
      youtube_trailer: "TLkA0RELQ1g",
      director: "Bassam Kurdali",
      actors: "Cas Jansen, Tygo Gernandt",
      cast: "Cas Jansen, Tygo Gernandt",
      description:
        "Two people explore a strange mechanical world, with the older one explaining its features, while the younger one remains unconvinced.",
      plot: "Two people explore a strange mechanical world, with the older one explaining its features, while the younger one remains unconvinced.",
      age: "",
      mpaa_rating: "G",
      rating_count_kinopoisk: 0,
      country: "Netherlands",
      genre: "Animation, Sci-Fi, Short",
      duration_secs: 654,
      duration: "00:10:54",
      bitrate: 0,
      video: {},
      audio: {},
    },
    movie_data: {
      stream_id: 4,
      name: "Elephant's Dream",
      added: "1704067200",
      category_id: "2",
      container_extension: "mp4",
      custom_sid: "",
      direct_source: "",
    },
  },
};

// ── Live TV ──────────────────────────────────────────────────────────────

export const LIVE_CATEGORIES = [
  { category_id: "10", category_name: "News", parent_id: 0 },
  { category_id: "11", category_name: "Entertainment", parent_id: 0 },
  { category_id: "12", category_name: "Test Channels", parent_id: 0 },
];

export const LIVE_STREAMS = [
  // ── News ──
  {
    num: 1,
    name: "CGTN English",
    stream_type: "live",
    stream_id: 101,
    stream_icon: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/CGTN.svg/200px-CGTN.svg.png",
    epg_channel_id: "cgtn_en",
    added: "1704067200",
    category_id: "10",
    custom_sid: "",
    tv_archive: 0,
    direct_source: "",
    tv_archive_duration: 0,
  },
  {
    num: 2,
    name: "CGTN French",
    stream_type: "live",
    stream_id: 102,
    stream_icon: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/CGTN.svg/200px-CGTN.svg.png",
    epg_channel_id: "cgtn_fr",
    added: "1704067200",
    category_id: "10",
    custom_sid: "",
    tv_archive: 0,
    direct_source: "",
    tv_archive_duration: 0,
  },
  {
    num: 3,
    name: "CGTN Documentary",
    stream_type: "live",
    stream_id: 103,
    stream_icon: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/CGTN.svg/200px-CGTN.svg.png",
    epg_channel_id: "cgtn_doc",
    added: "1704067200",
    category_id: "10",
    custom_sid: "",
    tv_archive: 0,
    direct_source: "",
    tv_archive_duration: 0,
  },
  {
    num: 4,
    name: "Al Jazeera English",
    stream_type: "live",
    stream_id: 104,
    stream_icon: "https://upload.wikimedia.org/wikipedia/en/thumb/f/f2/Aljazeera.svg/200px-Aljazeera.svg.png",
    epg_channel_id: "aljazeera_en",
    added: "1704067200",
    category_id: "10",
    custom_sid: "",
    tv_archive: 0,
    direct_source: "",
    tv_archive_duration: 0,
  },
  {
    num: 5,
    name: "France 24 English",
    stream_type: "live",
    stream_id: 105,
    stream_icon: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/France_24_logo_%282018%29.svg/200px-France_24_logo_%282018%29.svg.png",
    epg_channel_id: "france24_en",
    added: "1704067200",
    category_id: "10",
    custom_sid: "",
    tv_archive: 0,
    direct_source: "",
    tv_archive_duration: 0,
  },
  {
    num: 6,
    name: "DW English",
    stream_type: "live",
    stream_id: 106,
    stream_icon: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Deutsche_Welle_logo.svg/200px-Deutsche_Welle_logo.svg.png",
    epg_channel_id: "dw_en",
    added: "1704067200",
    category_id: "10",
    custom_sid: "",
    tv_archive: 0,
    direct_source: "",
    tv_archive_duration: 0,
  },
  // ── Entertainment ──
  {
    num: 7,
    name: "Cine.AR",
    stream_type: "live",
    stream_id: 107,
    stream_icon: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Logo_CINE.AR.svg/200px-Logo_CINE.AR.svg.png",
    epg_channel_id: "cinear",
    added: "1704067200",
    category_id: "11",
    custom_sid: "",
    tv_archive: 0,
    direct_source: "",
    tv_archive_duration: 0,
  },
  {
    num: 8,
    name: "DeporTV",
    stream_type: "live",
    stream_id: 108,
    stream_icon: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/DeporTV_%28Logo%29.svg/200px-DeporTV_%28Logo%29.svg.png",
    epg_channel_id: "deportv",
    added: "1704067200",
    category_id: "11",
    custom_sid: "",
    tv_archive: 0,
    direct_source: "",
    tv_archive_duration: 0,
  },
  {
    num: 9,
    name: "TV Publica Argentina",
    stream_type: "live",
    stream_id: 109,
    stream_icon: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Logo_TV_P%C3%BAblica_Argentina.svg/200px-Logo_TV_P%C3%BAblica_Argentina.svg.png",
    epg_channel_id: "tvpublica",
    added: "1704067200",
    category_id: "11",
    custom_sid: "",
    tv_archive: 0,
    direct_source: "",
    tv_archive_duration: 0,
  },
  {
    num: 10,
    name: "Encuentro",
    stream_type: "live",
    stream_id: 110,
    stream_icon: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Canal_Encuentro.svg/200px-Canal_Encuentro.svg.png",
    epg_channel_id: "encuentro",
    added: "1704067200",
    category_id: "11",
    custom_sid: "",
    tv_archive: 0,
    direct_source: "",
    tv_archive_duration: 0,
  },
  // ── Test Channels ──
  {
    num: 11,
    name: "Test Pattern (HLS)",
    stream_type: "live",
    stream_id: 111,
    stream_icon: POSTERS.testPattern,
    epg_channel_id: "test_pattern",
    added: "1704067200",
    category_id: "12",
    custom_sid: "",
    tv_archive: 0,
    direct_source: "",
    tv_archive_duration: 0,
  },
  {
    num: 12,
    name: "Nature Loop (HLS)",
    stream_type: "live",
    stream_id: 112,
    stream_icon: POSTERS.nature,
    epg_channel_id: "nature_loop",
    added: "1704067200",
    category_id: "12",
    custom_sid: "",
    tv_archive: 0,
    direct_source: "",
    tv_archive_duration: 0,
  },
];

// ── Series ───────────────────────────────────────────────────────────────

export const SERIES_CATEGORIES = [
  { category_id: "20", category_name: "Animation", parent_id: 0 },
];

export const SERIES_LIST = [
  {
    num: 1,
    name: "Blender Open Movies",
    series_id: 501,
    cover: POSTERS.blenderSeries,
    plot: "A collection of award-winning open-source animated short films produced by the Blender Foundation.",
    cast: "Various",
    director: "Various",
    genre: "Animation",
    release_date: "2008-01-01",
    last_modified: "1704067200",
    rating: "8.0",
    rating_5based: 4.0,
    backdrop_path: [],
    youtube_trailer: "",
    episode_run_time: "14",
    category_id: "20",
  },
];

export const SERIES_INFO: Record<number, object> = {
  501: {
    seasons: [
      {
        air_date: "2008-04-10",
        episode_count: 3,
        id: 1,
        name: "Season 1",
        overview: "The original trilogy of Blender Foundation open movies.",
        season_number: 1,
        cover: POSTERS.blenderSeries,
        cover_big: POSTERS.blenderSeries,
      },
    ],
    info: {
      name: "Blender Open Movies",
      cover: POSTERS.blenderSeries,
      plot: "A collection of award-winning open-source animated short films produced by the Blender Foundation.",
      cast: "Various",
      director: "Various",
      genre: "Animation",
      release_date: "2008-01-01",
      last_modified: "1704067200",
      rating: "8.0",
      rating_5based: 4.0,
      backdrop_path: [],
      youtube_trailer: "",
      episode_run_time: "14",
      category_id: "20",
    },
    episodes: {
      "1": [
        {
          id: "1001",
          episode_num: 1,
          title: "Big Buck Bunny",
          container_extension: "mp4",
          info: {
            movie_image: POSTERS.bigBuckBunny,
            plot: "A large and lovable rabbit deals with three tiny bullies.",
            duration_secs: 596,
            duration: "00:09:56",
            rating: 8.0,
            name: "Big Buck Bunny",
            season: 1,
          },
          custom_sid: "",
          added: "1704067200",
          season: 1,
          direct_source: "",
        },
        {
          id: "1002",
          episode_num: 2,
          title: "Sintel",
          container_extension: "mp4",
          info: {
            movie_image: POSTERS.sintel,
            plot: "A lonely young woman embarks on a dangerous quest to find her dragon friend.",
            duration_secs: 888,
            duration: "00:14:48",
            rating: 7.5,
            name: "Sintel",
            season: 1,
          },
          custom_sid: "",
          added: "1704067200",
          season: 1,
          direct_source: "",
        },
        {
          id: "1003",
          episode_num: 3,
          title: "Tears of Steel",
          container_extension: "mp4",
          info: {
            movie_image: POSTERS.tearsOfSteel,
            plot: "In an apocalyptic future, soldiers try to stop an army of robots.",
            duration_secs: 734,
            duration: "00:12:14",
            rating: 7.0,
            name: "Tears of Steel",
            season: 1,
          },
          custom_sid: "",
          added: "1704067200",
          season: 1,
          direct_source: "",
        },
      ],
    },
  },
};
